# argocd_deploy_repo2/hello/charts/greet/templates/deploy.yaml

apiVersion: v1
kind: Service
metadata:
  name: greet-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: greet